/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Street_n_buildings.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function StreetNBuildings(props) {
  const model = React.useRef();
  const { nodes, materials } = useGLTF("./models/Street_n_buildings.glb");
  useFrame((state) => {
    model.current.rotation.y = state.pointer.x * 0.1;
    model.current.rotation.x = -state.pointer.y * 0.1;
  });
  return (
    <group {...props} dispose={null} ref={model}>
      <mesh geometry={nodes.Plane002.geometry} material={materials.Street} />
      <mesh
        geometry={nodes.building_hotel.geometry}
        material={materials.hotel_wall_second_floor}
      />
      <mesh geometry={nodes.Wall001.geometry} material={materials.Wall} />
      <mesh
        geometry={nodes.Post_light.geometry}
        material={materials.light_post}
      />
      <mesh
        geometry={nodes.Air_conditioner001.geometry}
        material={materials.air_conditioner}
      />
      <mesh geometry={nodes.Letter.geometry} material={materials.Letter} />
      <mesh geometry={nodes.Cube.geometry} material={materials.pink_light} />
      <mesh
        geometry={nodes.building_hotel002.geometry}
        material={materials.HOTEL}
      />
      <mesh geometry={nodes.post002.geometry} material={materials.light_post} />
      <mesh
        geometry={nodes.Wall002.geometry}
        material={materials["Wall.001"]}
      />
      <mesh
        geometry={nodes.building_parcking_pipe.geometry}
        material={materials.parking_pipes}
      />
      <mesh
        geometry={nodes.building_parcking_pipe001.geometry}
        material={materials["parking_pipes.001"]}
      />
      <mesh
        geometry={nodes.building_hotel_window_frame.geometry}
        material={materials.window_frame}
      />
      <mesh
        geometry={nodes.building_hotel003.geometry}
        material={materials.hotel_third_floor_wall_grey}
      />
      <mesh geometry={nodes.hotel_pipe.geometry} material={materials.pipes} />
      <mesh
        geometry={nodes.building_hotel_inside.geometry}
        material={materials["Wall-grey"]}
      />
      <mesh geometry={nodes.hotel_cords.geometry} material={materials.Cord} />
      <mesh geometry={nodes.fence.geometry} material={materials.fence} />
      <mesh geometry={nodes.pipes.geometry} material={materials.pipes} />
      <mesh
        geometry={nodes.fence_pillar.geometry}
        material={materials.light_post}
      />
      <mesh
        geometry={nodes.house_plants_spot.geometry}
        material={materials["Wall-grey"]}
      />
      <mesh
        geometry={nodes.hotel_windows.geometry}
        material={materials.hotel_window}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials.parking_wall_gry}
      />
      <mesh
        geometry={nodes.Cube005_1.geometry}
        material={materials.parking_windows}
      />
      <mesh
        geometry={nodes.Cube005_2.geometry}
        material={materials["wall-bathroom"]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials.House_window}
      />
      <mesh
        geometry={nodes.Cube007_1.geometry}
        material={materials.house_wall_grey}
      />
      <mesh geometry={nodes.Plane007.geometry} material={materials.Street} />
      <mesh
        geometry={nodes.Plane007_1.geometry}
        material={materials.Sidewalk}
      />
      <mesh
        geometry={nodes.Plane007_2.geometry}
        material={materials.SidewalkEdge}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials["Wall-grey"]}
      />
      <mesh geometry={nodes.Cube011_1.geometry} material={materials.Whindow} />
      <mesh geometry={nodes.Cube011_2.geometry} material={materials.Door} />
      <mesh
        geometry={nodes.Cube011_3.geometry}
        material={materials.window_frame}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials.hotel_first_floor_wall_gray}
      />
      <mesh geometry={nodes.Cube019_1.geometry} material={materials.Door} />
      <mesh
        geometry={nodes.Cube019_2.geometry}
        material={materials.wall_bricks}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials.window_frame_second_floor}
      />
      <mesh
        geometry={nodes.Cube009_1.geometry}
        material={materials.hotel_second_floor_fence}
      />
      <mesh geometry={nodes.Cube031.geometry} material={materials.bush} />
      <mesh geometry={nodes.Cube031_1.geometry} material={materials.pot} />
    </group>
  );
}

useGLTF.preload("./models/Street_n_buildings.glb");
